# Generated by Django 5.2.2 on 2025-06-16 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address for newsletter subscription', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, help_text='Date when the subscription was created')),
                ('unsubscribe_token', models.CharField(blank=True, help_text='Token for unsubscribing', max_length=64, unique=True)),
                ('source', models.CharField(default='blog', help_text='Source of subscription (e.g., blog, footer, popup)', max_length=50)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscription_date'],
            },
        ),
    ]
