# Generated by Django 5.2.2 on 2025-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='solution',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
